[package]
name = "app_root_client"
version = "0.1.0"
edition = "2024"

[features]
default = ["web"]
web = ["dioxus/web"]
# desktop = ["dioxus/desktop"]
# mobile = ["dioxus/mobile"]

[dependencies]
accounting_engine = { workspace = true }
cache = { workspace = true }
infrastructure = { workspace = true }
kernel = { workspace = true }
patterns = { workspace = true }
utility = { workspace = true }
utility_ui = { workspace = true, features = ["ui"] }

use_case_create_account = { workspace = true, features = ["client", "cache", "ui"] }
use_case_get_all_accounts = { workspace = true, features = ["client", "cache", "ui"] }

anyhow = { workspace = true }
serde = { workspace = true }

dioxus = { workspace = true }
dioxus-logger = { workspace = true }
