[workspace]
resolver = "2"
members = [
    # "accounting_lib",
    "accounting_ui",
    "adapters",
    "cache_rusqlite",
    "db_client_cockroach",
    "my_core",
    "server_actix",
]

[workspace.dependencies]
adapters = { path = "./adapters" }
cache_rusqlite = { path = "./cache_rusqlite" }
db_client_cockroach = { path = "./db_client_cockroach" }
derive_more = { version = "2.1.1", features = ["full"] }
dioxus-logger = "0.7.9"
futures-util = "0.3.32"
my_core = { path = "./my_core" }
rustls = "0.23.42"
rustls-pemfile = "2.2.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.53.0"
uuid = { version = "1.24.0", features = ["v7", "serde", "js"] }

[profile.dev]
opt-level = 0
