unstable_features = true
imports_granularity = "Item"
group_imports = "One"

force_multiline_blocks=true
overflow_delimited_expr = true
reorder_impl_items=true
struct_field_align_threshold=1000
struct_lit_single_line=false
use_field_init_shorthand=true
use_small_heuristics="Off"
use_try_shorthand=true

format_macro_matchers=true
format_macro_bodies=true
hex_literal_case="Upper"
float_literal_trailing_zero="Always"
single_line_if_else_max_width=0
single_line_let_else_max_width=0
