[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[features]
ui = []
cache = []
database = []

[dependencies]
infrastructure = { workspace = true }
utility = { workspace = true }
utility_ui = { workspace = true }

anyhow = { workspace = true }
dyn-clone = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }
