[package]
name = "use_case_create_account"
version = "0.1.0"
edition = "2024"

[features]
ui = ["dioxus"]
cache = ["dep:cache", "rusqlite"]
database = ["dep:database"]
client = []
server = []
wires = []

[dependencies]
infrastructure = { workspace = true }
kernel = { workspace = true }
use_case_get_all_accounts = { workspace = true }
utility = { workspace = true }
utility_ui = { workspace = true }

cache = { workspace = true, optional = true }
database = { workspace = true, optional = true }

anyhow = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }

dioxus = { workspace = true, optional = true }
rusqlite = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
