[package]
name = "db_client_cockroach"
version = "0.1.0"
edition = "2024"

[dependencies]
adapters = { workspace = true }
my_core = { workspace = true }

deadpool-postgres = "0.14.1"
tokio-postgres = { version = "0.7.16", features = ["with-uuid-1"]}
tokio = { workspace = true }
uuid = { workspace = true }
