[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel = { workspace = true }
utility = { workspace = true }

anyhow = { workspace = true }
serde = { workspace = true }

deadpool-postgres = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
