[package]
name = "adapters"
version = "0.1.0"
edition = "2024"

[dependencies]
my_core = { workspace = true }

derive_more = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
futures-util = { workspace = true }
futures = "0.3.32"
postcard = { version = "1.1.3", features = ["alloc"] }
getrandom = { version = "0.4.3", features = ["wasm_js"] }
chrono = "0.4.45"
regex = "1.12.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio-tungstenite = "0.29.0"
tokio = { workspace = true , features = ["macros"]}
argon2 = "0.5.3"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.4.0" , features = ["futures"]}
gloo-net = "0.7.0"
wasm-bindgen-futures = "0.4.76"
