[package]
name = "server_actix"
version = "0.1.0"
edition = "2024"

[dependencies]
my_core = { workspace = true }
adapters = { workspace = true }
db_client_cockroach = { workspace = true }

actix-web = { version = "4.13.0" , features = ["rustls-0_23"]}
actix-cors = "0.7.1"
actix-ws = "0.4.0"
futures-util = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
