[package]
name = "use_case_get_all_accounts"
version = "0.1.0"
edition = "2024"

[features]
ui = []
cache = ["dep:cache"]
database = ["uuid", "dep:database"]
client = []
server = []
wires = []

[dependencies]
infrastructure = { workspace = true }
kernel = { workspace = true }
utility = { workspace = true }

cache = { workspace = true, optional = true }
database = { workspace = true, optional = true }

anyhow = { workspace = true }
dyn-clone = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }

uuid = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
