[package]
name = "use_case_get_all_accounts"
version = "0.1.0"
edition = "2024"

[features]
infrastructure = []
ui = []
cache = []
database = []
client = []
server = []

[dependencies]
infrastructure = { workspace = true }
kernel = { workspace = true }
utility = { workspace = true }

anyhow = { workspace = true }
dyn-clone = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }
