[package]
name = "client_tokio_tungstenite"
version = "0.1.0"
edition = "2024"

[dependencies]
my_core = { workspace = true }
impls_for_wasm = { workspace = true }

tokio = { workspace = true, features = ["rt", "sync", "macros"] }
tokio-tungstenite-wasm = { workspace = true }
wasm-bindgen-futures = { workspace = true }
futures-util = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
