[package]
name = "client_tokio_tungstenite"
version = "0.1.0"
edition = "2024"

[dependencies]
my_core = { workspace = true }
impls_for_wasm = { workspace = true }

# tokio = { workspace = true }
# tokio-tungstenite = { workspace = true }
tokio-tungstenite-wasm = { workspace = true }
futures-util = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
