[package]
name = "accounting_ui"
version = "0.1.0"
authors = ["hashem"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_core = { workspace = true }
client_tokio_tungstenite = { workspace = true }
# client_gloo_net = { workspace = true }
impls_for_wasm = { workspace = true }

dioxus = { workspace = true }
dioxus-logger = { workspace = true }
console_error_panic_hook = { workspace = true }


[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
